runtime: nodejs20

# Environment variables for Google Cloud Run
env_variables:
  NODE_ENV: production
  PORT: 8080
  
  # Database configuration (to be set in Cloud Console)
  # DB_HOST: YOUR_CLOUD_SQL_IP
  # DB_USER: YOUR_DB_USER  
  # DB_PASSWORD: YOUR_DB_PASSWORD
  # DB_NAME: motornation
  # DB_PORT: 5432
  
  # YouTube API
  # YT_API_KEY: YOUR_YOUTUBE_API_KEY
  # CHANNEL_ID: YOUR_CHANNEL_ID
  
  # Google Cloud Storage
  # GOOGLE_CLOUD_PROJECT_ID: motornation-466804
  # GOOGLE_CLOUD_BUCKET_NAME_NEWS: news-article-images-mn
  # GOOGLE_CLOUD_BUCKET_NAME_REVIEWS: review-article-images-mn
  # GOOGLE_CLOUD_KEY_FILE: motornation-466804-6b7a914a1fd1.json

# Automatic scaling configuration
automatic_scaling:
  min_instances: 0
  max_instances: 10
  target_cpu_utilization: 0.6

# Health check configuration
readiness_check:
  path: "/health"
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2

liveness_check:
  path: "/health"
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 4
  success_threshold: 2

# Resource configuration
resources:
  cpu: 1
  memory_gb: 1